// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task_U.Data;

#nullable disable

namespace Task_U.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314142158_MaxHealthUpdate")]
    partial class MaxHealthUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Task_U.Core.InimigoBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Atk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrystalDrop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeathQuote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT");

                    b.Property<int>("HabilidadeChance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HpMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemDropId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inimigos");
                });

            modelBuilder.Entity("Task_U.Core.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Atr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("Task_U.Core.ItemInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InventarioItens");
                });

            modelBuilder.Entity("Task_U.Core.PersonagemBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Atk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int>("HpMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummonQuote")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personagens");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PersonagemBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Task_U.Core.PersonagemInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InventarioPersonagens");
                });

            modelBuilder.Entity("Task_U.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LegId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("banners");
                });

            modelBuilder.Entity("Task_U.Models.BaseTarefas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BaseTarefas");
                });

            modelBuilder.Entity("Task_U.Models.SideQuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SideQuests");
                });

            modelBuilder.Entity("Task_U.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("Task_U.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Crystals")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemAtivoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastBannerUpdate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonagemAtivoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PityEpic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PityLeg")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("lastLogin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemAtivoId");

                    b.HasIndex("PersonagemAtivoId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Task_U.Core.Apostador", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.Property<int>("BaseAtk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusDMG")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Win")
                        .HasColumnType("INTEGER");

                    b.ToTable("Personagens", t =>
                        {
                            t.Property("BaseAtk")
                                .HasColumnName("Apostador_BaseAtk");

                            t.Property("BonusDMG")
                                .HasColumnName("Apostador_BonusDMG");
                        });

                    b.HasDiscriminator().HasValue("Apostador");
                });

            modelBuilder.Entity("Task_U.Core.Barbaro", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.Property<int>("BaseAtk")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Barbaro");
                });

            modelBuilder.Entity("Task_U.Core.Grafiteiro", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("Grafiteiro");
                });

            modelBuilder.Entity("Task_U.Core.Moon", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.Property<int>("BonusDMG")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MoonState")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Moon");
                });

            modelBuilder.Entity("Task_U.Core.Voodo", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("Voodo");
                });

            modelBuilder.Entity("Task_U.Models.User", b =>
                {
                    b.HasOne("Task_U.Core.Item", "ItemAtivo")
                        .WithMany()
                        .HasForeignKey("ItemAtivoId");

                    b.HasOne("Task_U.Core.PersonagemBase", "PersonagemAtivo")
                        .WithMany()
                        .HasForeignKey("PersonagemAtivoId");

                    b.Navigation("ItemAtivo");

                    b.Navigation("PersonagemAtivo");
                });
#pragma warning restore 612, 618
        }
    }
}
