// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task_U.Data;

#nullable disable

namespace Task_U.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Task_U.Core.InimigoBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Atk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrystalDrop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeathQuote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int>("HabilidadeChance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HpMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemDropId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tipoBoss")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Inimigos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("InimigoBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Task_U.Core.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Atr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("exclLoja")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Itens");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Task_U.Core.ItemInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InventarioItens");
                });

            modelBuilder.Entity("Task_U.Core.PersonagemBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Atk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int>("HpMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummonQuote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personagens");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PersonagemBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Task_U.Core.PersonagemInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodesNivel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InventarioPersonagens");
                });

            modelBuilder.Entity("Task_U.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LegId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("banners");
                });

            modelBuilder.Entity("Task_U.Models.BaseTarefas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BaseTarefas");
                });

            modelBuilder.Entity("Task_U.Models.Loja", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("comprado")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("personagem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("personagemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("preco")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("loja");
                });

            modelBuilder.Entity("Task_U.Models.SideQuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Dif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SideQuests");
                });

            modelBuilder.Entity("Task_U.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Dif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("Task_U.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Crystals")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DerrotouInimigo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InimigoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastBannerUpdate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLojaUpdate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PityEpic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PityLeg")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Slot1_ItemAtivoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Slot1_PersonagemAtivoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Slot2_ItemAtivoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Slot2_PersonagemAtivoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("lastLogin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slot1_ItemAtivoId");

                    b.HasIndex("Slot1_PersonagemAtivoId");

                    b.HasIndex("Slot2_ItemAtivoId");

                    b.HasIndex("Slot2_PersonagemAtivoId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Task_U.Core.Aranha", b =>
                {
                    b.HasBaseType("Task_U.Core.InimigoBase");

                    b.HasDiscriminator().HasValue("Aranha");
                });

            modelBuilder.Entity("Task_U.Core.Banshee", b =>
                {
                    b.HasBaseType("Task_U.Core.InimigoBase");

                    b.HasDiscriminator().HasValue("Banshee");
                });

            modelBuilder.Entity("Task_U.Core.DronEscaravelho", b =>
                {
                    b.HasBaseType("Task_U.Core.InimigoBase");

                    b.HasDiscriminator().HasValue("DronEscaravelho");
                });

            modelBuilder.Entity("Task_U.Core.Enemies.DragaoEgito", b =>
                {
                    b.HasBaseType("Task_U.Core.InimigoBase");

                    b.HasDiscriminator().HasValue("DragaoEgito");
                });

            modelBuilder.Entity("Task_U.Core.Enemies.GreedFollower", b =>
                {
                    b.HasBaseType("Task_U.Core.InimigoBase");

                    b.HasDiscriminator().HasValue("GreedFollower");
                });

            modelBuilder.Entity("Task_U.Core.Enemies.Kappa", b =>
                {
                    b.HasBaseType("Task_U.Core.InimigoBase");

                    b.HasDiscriminator().HasValue("Kappa");
                });

            modelBuilder.Entity("Task_U.Core.Enemies.Karakasa", b =>
                {
                    b.HasBaseType("Task_U.Core.InimigoBase");

                    b.HasDiscriminator().HasValue("Karakasa");
                });

            modelBuilder.Entity("Task_U.Core.Fada", b =>
                {
                    b.HasBaseType("Task_U.Core.InimigoBase");

                    b.HasDiscriminator().HasValue("Fada");
                });

            modelBuilder.Entity("Task_U.Core.FadaRa", b =>
                {
                    b.HasBaseType("Task_U.Core.InimigoBase");

                    b.HasDiscriminator().HasValue("FadaRa");
                });

            modelBuilder.Entity("Task_U.Core.Gargula", b =>
                {
                    b.HasBaseType("Task_U.Core.InimigoBase");

                    b.HasDiscriminator().HasValue("Gargula");
                });

            modelBuilder.Entity("Task_U.Core.Mumia", b =>
                {
                    b.HasBaseType("Task_U.Core.InimigoBase");

                    b.HasDiscriminator().HasValue("Mumia");
                });

            modelBuilder.Entity("Task_U.Core.Oni", b =>
                {
                    b.HasBaseType("Task_U.Core.InimigoBase");

                    b.HasDiscriminator().HasValue("Oni");
                });

            modelBuilder.Entity("Task_U.Core.TechGoblin", b =>
                {
                    b.HasBaseType("Task_U.Core.InimigoBase");

                    b.HasDiscriminator().HasValue("TechGoblin");
                });

            modelBuilder.Entity("Task_U.Core.Itens.AdagaDeVidro", b =>
                {
                    b.HasBaseType("Task_U.Core.Item");

                    b.HasDiscriminator().HasValue("AdagaDeVidro");
                });

            modelBuilder.Entity("Task_U.Core.Itens.AdagaDoSacrificio", b =>
                {
                    b.HasBaseType("Task_U.Core.Item");

                    b.HasDiscriminator().HasValue("AdagaDoSacrificio");
                });

            modelBuilder.Entity("Task_U.Core.Itens.AmpulhetaAreia", b =>
                {
                    b.HasBaseType("Task_U.Core.Item");

                    b.HasDiscriminator().HasValue("AmpulhetaAreia");
                });

            modelBuilder.Entity("Task_U.Core.Itens.AnkhBronze", b =>
                {
                    b.HasBaseType("Task_U.Core.Item");

                    b.HasDiscriminator().HasValue("AnkhBronze");
                });

            modelBuilder.Entity("Task_U.Core.Itens.CapaMesquinha", b =>
                {
                    b.HasBaseType("Task_U.Core.Item");

                    b.HasDiscriminator().HasValue("CapaMesquinha");
                });

            modelBuilder.Entity("Task_U.Core.Itens.FragmentoEstelar", b =>
                {
                    b.HasBaseType("Task_U.Core.Item");

                    b.HasDiscriminator().HasValue("FragmentoEstelar");
                });

            modelBuilder.Entity("Task_U.Core.Itens.LuvaImpiedosa", b =>
                {
                    b.HasBaseType("Task_U.Core.Item");

                    b.HasDiscriminator().HasValue("LuvaImpiedosa");
                });

            modelBuilder.Entity("Task_U.Core.Itens.MantoDoSacrificio", b =>
                {
                    b.HasBaseType("Task_U.Core.Item");

                    b.HasDiscriminator().HasValue("MantoDoSacrificio");
                });

            modelBuilder.Entity("Task_U.Core.Itens.MoedaDaSorte", b =>
                {
                    b.HasBaseType("Task_U.Core.Item");

                    b.HasDiscriminator().HasValue("MoedaDaSorte");
                });

            modelBuilder.Entity("Task_U.Core.Itens.aranhaItem", b =>
                {
                    b.HasBaseType("Task_U.Core.Item");

                    b.HasDiscriminator().HasValue("aranhaItem");
                });

            modelBuilder.Entity("Task_U.Core.Itens.fadaNucleo", b =>
                {
                    b.HasBaseType("Task_U.Core.Item");

                    b.HasDiscriminator().HasValue("fadaNucleo");
                });

            modelBuilder.Entity("Task_U.Core.Itens.grilhaoGreed", b =>
                {
                    b.HasBaseType("Task_U.Core.Item");

                    b.HasDiscriminator().HasValue("grilhaoGreed");
                });

            modelBuilder.Entity("Task_U.Core.Itens.oniHeart", b =>
                {
                    b.HasBaseType("Task_U.Core.Item");

                    b.HasDiscriminator().HasValue("oniHeart");
                });

            modelBuilder.Entity("Task_U.Core.Apostador", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.Property<int>("BaseAtk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Win")
                        .HasColumnType("INTEGER");

                    b.ToTable("Personagens", t =>
                        {
                            t.Property("BaseAtk")
                                .HasColumnName("Apostador_BaseAtk");
                        });

                    b.HasDiscriminator().HasValue("Apostador");
                });

            modelBuilder.Entity("Task_U.Core.Barbaro", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.Property<int>("BaseAtk")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Barbaro");
                });

            modelBuilder.Entity("Task_U.Core.Entities.Atacante", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("Atacante");
                });

            modelBuilder.Entity("Task_U.Core.Entities.Bennu", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("Bennu");
                });

            modelBuilder.Entity("Task_U.Core.Entities.Cleaner", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("Cleaner");
                });

            modelBuilder.Entity("Task_U.Core.Entities.Domina", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("Domina");
                });

            modelBuilder.Entity("Task_U.Core.Entities.Exorcist", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("Exorcist");
                });

            modelBuilder.Entity("Task_U.Core.Entities.Lab", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("Lab");
                });

            modelBuilder.Entity("Task_U.Core.Entities.Ladra", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("Ladra");
                });

            modelBuilder.Entity("Task_U.Core.Entities.Priest", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("Priest");
                });

            modelBuilder.Entity("Task_U.Core.Entities.SlimeA", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("SlimeA");
                });

            modelBuilder.Entity("Task_U.Core.Entities.Star", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("Star");
                });

            modelBuilder.Entity("Task_U.Core.Entities.Vampire", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("Vampire");
                });

            modelBuilder.Entity("Task_U.Core.Grafiteiro", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("Grafiteiro");
                });

            modelBuilder.Entity("Task_U.Core.Moon", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.Property<int>("BonusDMG")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MoonState")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Moon");
                });

            modelBuilder.Entity("Task_U.Core.Police", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("Police");
                });

            modelBuilder.Entity("Task_U.Core.Soul", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("Soul");
                });

            modelBuilder.Entity("Task_U.Core.Voodo", b =>
                {
                    b.HasBaseType("Task_U.Core.PersonagemBase");

                    b.HasDiscriminator().HasValue("Voodo");
                });

            modelBuilder.Entity("Task_U.Models.User", b =>
                {
                    b.HasOne("Task_U.Core.Item", "Slot1_ItemAtivo")
                        .WithMany()
                        .HasForeignKey("Slot1_ItemAtivoId");

                    b.HasOne("Task_U.Core.PersonagemBase", "Slot1_PersonagemAtivo")
                        .WithMany()
                        .HasForeignKey("Slot1_PersonagemAtivoId");

                    b.HasOne("Task_U.Core.Item", "Slot2_ItemAtivo")
                        .WithMany()
                        .HasForeignKey("Slot2_ItemAtivoId");

                    b.HasOne("Task_U.Core.PersonagemBase", "Slot2_PersonagemAtivo")
                        .WithMany()
                        .HasForeignKey("Slot2_PersonagemAtivoId");

                    b.Navigation("Slot1_ItemAtivo");

                    b.Navigation("Slot1_PersonagemAtivo");

                    b.Navigation("Slot2_ItemAtivo");

                    b.Navigation("Slot2_PersonagemAtivo");
                });
#pragma warning restore 612, 618
        }
    }
}
